### ISSUE TITLE
Automate Controller Tasks

### ISSUE THREAD

**Issue by ghost** [lwileczek/k8s-quick-start#2]
## Goal

Automate the tasks on the controller server that are in files/controller_tasks

Everything but the actually execution of `ansible-playbook cluster.yml` should be done in case you customization are required. 

### Tasks

  - [x] declare IPS variable
  - [x] run `contrib/inventory_builder/inventory.py`
  - [x] update `inventory/group_vars/all/all.yml` with ssh user and interpreter
  - [x] download **kubectl**  and add it to the path
  - [x] Add bash file to pull `/etc/kubectl/admin.conf` from one of the master nodes

### Why

Because the more automation the better. I'm LAZY

**Comment by lwileczek** [comment]
Cannot copy `/etc/kubectl/admin.conf` until after kubesrpay has deployed, which I do not want to always run before customizing the deployment.  I will add a variable which will conditionally run `kubespray/cluster.yml` and then copy that file.

**Comment by lwileczek** [comment]
Automatically running the deployment is tough and not proper. I did add a bash file to the home directory of the controller node called `get_config.sh` that retrieves the `/etc/kubernetes/admin.conf` file for you and puts it in the proper spot so kubectl works.
